# Generated by Django 3.1 on 2020-08-23 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('calorie_density', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, default='', max_length=200)),
                ('servings_per_unit', models.IntegerField(blank=True)),
                ('expiration_period', models.IntegerField(blank=True)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='rms_core.ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date added')),
                ('instructions', models.CharField(blank=True, default='', max_length=200)),
                ('serves', models.IntegerField()),
                ('prep_time', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('seasonality', models.CharField(blank=True, default='', max_length=200)),
                ('rating', models.IntegerField()),
                ('ingredients', models.ManyToManyField(to='rms_core.Ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeInstances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date made')),
                ('comments', models.CharField(blank=True, default='', max_length=200)),
                ('changes', models.CharField(blank=True, default='todo', max_length=200)),
                ('rating', models.IntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='rms_core.recipes')),
            ],
        ),
        migrations.CreateModel(
            name='Pantry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servings_remaining', models.IntegerField(blank=True)),
                ('expiration_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date expires')),
                ('supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='rms_core.supplies')),
            ],
        ),
    ]
