# Generated by Django 3.1 on 2020-08-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
